# Generated by Django 3.2.8 on 2021-12-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournaments', '0002_auto_20211209_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentteam',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
